-- AMIS Student Records Insertion SQL Script
-- Generated on 2026-06-13 23:55:19
START TRANSACTION;

-- Student: AYRAH JULHAMID MURAJI (Kinder 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MURAJI', 'parent.muraji.919@amis.test', 'parent_muraji_362', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Kinder 2', 'AYRAH', 'MURAJI', 'JULHAMID', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.muraji.919@amis.test', 'FAMILY MURAJI', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260001', '260001mayrah@amis.edu.ph', '260001mayrah@amis.edu.ph', 'Amis@ERERB23', 'Kinder 2', '2026-2027', NOW(), NOW());

-- Student: MARYAM KHAISA ALIH (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ALIH', 'parent.alih.227@amis.test', 'parent_alih_670', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 1', 'MARYAM', 'ALIH', 'KHAISA', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.alih.227@amis.test', 'FAMILY ALIH', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260002', '260002amaryam@amis.edu.ph', '260002amaryam@amis.edu.ph', 'Amis@THAIT94', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: IBRAHIM TARANG TULABIN (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY TULABIN', 'parent.tulabin.153@amis.test', 'parent_tulabin_827', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 1', 'IBRAHIM', 'TULABIN', 'TARANG', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.tulabin.153@amis.test', 'FAMILY TULABIN', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260003', '260003tibrahim@amis.edu.ph', '260003tibrahim@amis.edu.ph', 'Amis@2CEZY90', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: ELHAM ABDURAJAK LADDJABASSAL (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY LADDJABASSAL', 'parent.laddjabassal.560@amis.test', 'parent_laddjabassal_888', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 1', 'ELHAM', 'LADDJABASSAL', 'ABDURAJAK', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.laddjabassal.560@amis.test', 'FAMILY LADDJABASSAL', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260004', '260004lelham@amis.edu.ph', '260004lelham@amis.edu.ph', 'Amis@QYSC913', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: ZAIN AYYUB NAVEED (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY NAVEED', 'parent.naveed.304@amis.test', 'parent_naveed_981', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 1', 'ZAIN', 'NAVEED', 'AYYUB', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.naveed.304@amis.test', 'FAMILY NAVEED', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260005', '260005nzain@amis.edu.ph', '260005nzain@amis.edu.ph', 'Amis@DS7B979', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: MIKAEEL TEOXON NATIVIDAD (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY NATIVIDAD', 'parent.natividad.505@amis.test', 'parent_natividad_828', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 1', 'MIKAEEL', 'NATIVIDAD', 'TEOXON', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.natividad.505@amis.test', 'FAMILY NATIVIDAD', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260006', '260006nmikaeel@amis.edu.ph', '260006nmikaeel@amis.edu.ph', 'Amis@8PCXJ19', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: AYMAAN JULHAMID MURAJI (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MURAJI', 'parent.muraji.456@amis.test', 'parent_muraji_125', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 1', 'AYMAAN', 'MURAJI', 'JULHAMID', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.muraji.456@amis.test', 'FAMILY MURAJI', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260007', '260007maymaan@amis.edu.ph', '260007maymaan@amis.edu.ph', 'Amis@LMJ3E48', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: KHALID MANGUDADATU MAGNO (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MAGNO', 'parent.magno.775@amis.test', 'parent_magno_715', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 1', 'KHALID', 'MAGNO', 'MANGUDADATU', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.magno.775@amis.test', 'FAMILY MAGNO', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260008', '260008mkhalid@amis.edu.ph', '260008mkhalid@amis.edu.ph', 'Amis@S2MXY35', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: HOOR AL-AIN SALASAIN MAKALUTANG (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MAKALUTANG', 'parent.makalutang.395@amis.test', 'parent_makalutang_246', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 1', 'HOOR AL-AIN', 'MAKALUTANG', 'SALASAIN', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.makalutang.395@amis.test', 'FAMILY MAKALUTANG', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260009', '260009mhoor@amis.edu.ph', '260009mhoor@amis.edu.ph', 'Amis@5FNN243', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: MALEEQA SALI ARASAD (Grade 1)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ARASAD', 'parent.arasad.784@amis.test', 'parent_arasad_710', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 1', 'MALEEQA', 'ARASAD', 'SALI', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.arasad.784@amis.test', 'FAMILY ARASAD', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260010', '260010amaleeqa@amis.edu.ph', '260010amaleeqa@amis.edu.ph', 'Amis@9R2IH30', 'Grade 1', '2026-2027', NOW(), NOW());

-- Student: ALI ELIZACH ABUBACAR CHAWAND WALA (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY CHAWAND WALA', 'parent.chawandwala.644@amis.test', 'parent_chawandwala_647', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 2', 'ALI ELIZACH', 'CHAWAND WALA', 'ABUBACAR', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.chawandwala.644@amis.test', 'FAMILY CHAWAND WALA', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260011', '260011cali@amis.edu.ph', '260011cali@amis.edu.ph', 'Amis@1CSLN36', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: RADIYAH OLIMPAIN KATOG (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY KATOG', 'parent.katog.907@amis.test', 'parent_katog_403', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 2', 'RADIYAH', 'KATOG', 'OLIMPAIN', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.katog.907@amis.test', 'FAMILY KATOG', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260012', '260012kradiyah@amis.edu.ph', '260012kradiyah@amis.edu.ph', 'Amis@2L5BW53', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: RAYAH OLIMPAIN KATOG (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY KATOG', 'parent.katog.655@amis.test', 'parent_katog_951', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 2', 'RAYAH', 'KATOG', 'OLIMPAIN', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.katog.655@amis.test', 'FAMILY KATOG', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260013', '260013krayah@amis.edu.ph', '260013krayah@amis.edu.ph', 'Amis@UKBGN37', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: MALEEHA SALI ARASAD (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ARASAD', 'parent.arasad.659@amis.test', 'parent_arasad_663', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 2', 'MALEEHA', 'ARASAD', 'SALI', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.arasad.659@amis.test', 'FAMILY ARASAD', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260014', '260014amaleeha@amis.edu.ph', '260014amaleeha@amis.edu.ph', 'Amis@WTRGM13', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: ABDUL CARIM GABRIEL ISMALI (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ISMALI', 'parent.ismali.889@amis.test', 'parent_ismali_717', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 2', 'ABDUL CARIM', 'ISMALI', 'GABRIEL', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.ismali.889@amis.test', 'FAMILY ISMALI', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260015', '260015iabdul@amis.edu.ph', '260015iabdul@amis.edu.ph', 'Amis@OTM6G15', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: ASIYAH MUDAG PANGANDAMAN (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY PANGANDAMAN', 'parent.pangandaman.562@amis.test', 'parent_pangandaman_878', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 2', 'ASIYAH', 'PANGANDAMAN', 'MUDAG', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.pangandaman.562@amis.test', 'FAMILY PANGANDAMAN', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260016', '260016pasiyah@amis.edu.ph', '260016pasiyah@amis.edu.ph', 'Amis@LXAA262', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: MISHA NAILAH MUROD AMPAC (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY AMPAC', 'parent.ampac.893@amis.test', 'parent_ampac_776', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Face-to-Face', 'NA', 'Grade 2', 'MISHA NAILAH', 'AMPAC', 'MUROD', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.ampac.893@amis.test', 'FAMILY AMPAC', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260017', '260017amisha@amis.edu.ph', '260017amisha@amis.edu.ph', 'Amis@RIENI49', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: KENAN RYYAN NATIVIDAD SEDOMAR (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY SEDOMAR', 'parent.sedomar.219@amis.test', 'parent_sedomar_144', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Face-to-Face', 'NA', 'Grade 2', 'KENAN RYYAN', 'SEDOMAR', 'NATIVIDAD', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.sedomar.219@amis.test', 'FAMILY SEDOMAR', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260018', '260018skenan@amis.edu.ph', '260018skenan@amis.edu.ph', 'Amis@P6VYK23', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: AISHA FATIMA BALDOMERO JUHAN (Grade 2)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY JUHAN', 'parent.juhan.221@amis.test', 'parent_juhan_308', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Face-to-Face', 'NA', 'Grade 2', 'AISHA FATIMA', 'JUHAN', 'BALDOMERO', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.juhan.221@amis.test', 'FAMILY JUHAN', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260019', '260019jaisha@amis.edu.ph', '260019jaisha@amis.edu.ph', 'Amis@45JR559', 'Grade 2', '2026-2027', NOW(), NOW());

-- Student: AFEEFA BAROH BAYAN (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY BAYAN', 'parent.bayan.319@amis.test', 'parent_bayan_977', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 3', 'AFEEFA', 'BAYAN', 'BAROH', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.bayan.319@amis.test', 'FAMILY BAYAN', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260020', '260020bafeefa@amis.edu.ph', '260020bafeefa@amis.edu.ph', 'Amis@RSWAT80', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: ZAINAB HADJI ABUBACAR ABDUL RAHMAN (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ABDUL RAHMAN', 'parent.abdulrahman.578@amis.test', 'parent_abdulrahman_108', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 3', 'ZAINAB HADJI', 'ABDUL RAHMAN', 'ABUBACAR', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.abdulrahman.578@amis.test', 'FAMILY ABDUL RAHMAN', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260021', '260021azainab@amis.edu.ph', '260021azainab@amis.edu.ph', 'Amis@PBAEY23', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: SEBASTIAN CASSIEL LOZERO MILLS (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MILLS', 'parent.mills.610@amis.test', 'parent_mills_323', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 3', 'SEBASTIAN CASSIEL', 'MILLS', 'LOZERO', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.mills.610@amis.test', 'FAMILY MILLS', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260022', '260022msebastian@amis.edu.ph', '260022msebastian@amis.edu.ph', 'Amis@ZVTSQ93', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: ANNIYA AYYUB NAVEED (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY NAVEED', 'parent.naveed.965@amis.test', 'parent_naveed_484', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 3', 'ANNIYA', 'NAVEED', 'AYYUB', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.naveed.965@amis.test', 'FAMILY NAVEED', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260023', '260023nanniya@amis.edu.ph', '260023nanniya@amis.edu.ph', 'Amis@BJCZZ36', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: OMER AYYUB NAVEED (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY NAVEED', 'parent.naveed.756@amis.test', 'parent_naveed_409', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 3', 'OMER', 'NAVEED', 'AYYUB', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.naveed.756@amis.test', 'FAMILY NAVEED', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260024', '260024nomer@amis.edu.ph', '260024nomer@amis.edu.ph', 'Amis@8OIET50', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: LAYYINA TEOXON NATIVIDAD (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY NATIVIDAD', 'parent.natividad.640@amis.test', 'parent_natividad_972', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 3', 'LAYYINA', 'NATIVIDAD', 'TEOXON', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.natividad.640@amis.test', 'FAMILY NATIVIDAD', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260025', '260025nlayyina@amis.edu.ph', '260025nlayyina@amis.edu.ph', 'Amis@BXJHK57', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: AYEESHA CANACAN ABBAS (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ABBAS', 'parent.abbas.357@amis.test', 'parent_abbas_619', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 3', 'AYEESHA', 'ABBAS', 'CANACAN', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.abbas.357@amis.test', 'FAMILY ABBAS', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260026', '260026aayeesha@amis.edu.ph', '260026aayeesha@amis.edu.ph', 'Amis@LHEBB92', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: IZZADDEEN SALASAIN MAKALUTANG (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MAKALUTANG', 'parent.makalutang.341@amis.test', 'parent_makalutang_996', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 3', 'IZZADDEEN', 'MAKALUTANG', 'SALASAIN', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.makalutang.341@amis.test', 'FAMILY MAKALUTANG', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260027', '260027mizzaddeen@amis.edu.ph', '260027mizzaddeen@amis.edu.ph', 'Amis@1CKXB38', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: KHYLIE KEEM LUPON APLAL (Grade 3)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY APLAL', 'parent.aplal.312@amis.test', 'parent_aplal_638', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Face-to-Face', 'NA', 'Grade 3', 'KHYLIE KEEM', 'APLAL', 'LUPON', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.aplal.312@amis.test', 'FAMILY APLAL', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260028', '260028akhylie@amis.edu.ph', '260028akhylie@amis.edu.ph', 'Amis@NXAPN62', 'Grade 3', '2026-2027', NOW(), NOW());

-- Student: ZAREENAH HADJI ABUBACAR ABDUL RAHMAN (Grade 4)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ABDUL RAHMAN', 'parent.abdulrahman.160@amis.test', 'parent_abdulrahman_287', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 4', 'ZAREENAH HADJI', 'ABDUL RAHMAN', 'ABUBACAR', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.abdulrahman.160@amis.test', 'FAMILY ABDUL RAHMAN', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260029', '260029azareenah@amis.edu.ph', '260029azareenah@amis.edu.ph', 'Amis@OLAKL80', 'Grade 4', '2026-2027', NOW(), NOW());

-- Student: SALMAN ABDURAJAK LADIMIR (Grade 4)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY LADIMIR', 'parent.ladimir.497@amis.test', 'parent_ladimir_680', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 4', 'SALMAN', 'LADIMIR', 'ABDURAJAK', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.ladimir.497@amis.test', 'FAMILY LADIMIR', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260030', '260030lsalman@amis.edu.ph', '260030lsalman@amis.edu.ph', 'Amis@0U1DB12', 'Grade 4', '2026-2027', NOW(), NOW());

-- Student: ZAHIR CANACAN ABBAS (Grade 4)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ABBAS', 'parent.abbas.134@amis.test', 'parent_abbas_547', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 4', 'ZAHIR', 'ABBAS', 'CANACAN', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.abbas.134@amis.test', 'FAMILY ABBAS', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260031', '260031azahir@amis.edu.ph', '260031azahir@amis.edu.ph', 'Amis@U96YM71', 'Grade 4', '2026-2027', NOW(), NOW());

-- Student: SHASMEEN  MIRA-ATO (Grade 4)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MIRA-ATO', 'parent.miraato.519@amis.test', 'parent_miraato_407', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 4', 'SHASMEEN', 'MIRA-ATO', '', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.miraato.519@amis.test', 'FAMILY MIRA-ATO', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260032', '260032mshasmeen@amis.edu.ph', '260032mshasmeen@amis.edu.ph', 'Amis@XGVVG89', 'Grade 4', '2026-2027', NOW(), NOW());

-- Student: YUSUF MIRA-ATO MIRA-ATO (Grade 4)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MIRA-ATO', 'parent.miraato.571@amis.test', 'parent_miraato_530', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 4', 'YUSUF', 'MIRA-ATO', 'MIRA-ATO', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.miraato.571@amis.test', 'FAMILY MIRA-ATO', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260033', '260033myusuf@amis.edu.ph', '260033myusuf@amis.edu.ph', 'Amis@5RZSD77', 'Grade 4', '2026-2027', NOW(), NOW());

-- Student: SHAMEEM SANGKI MANGUDADATU (Grade 4)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MANGUDADATU', 'parent.mangudadatu.972@amis.test', 'parent_mangudadatu_981', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Face-to-Face', 'NA', 'Grade 4', 'SHAMEEM', 'MANGUDADATU', 'SANGKI', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.mangudadatu.972@amis.test', 'FAMILY MANGUDADATU', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260034', '260034mshameem@amis.edu.ph', '260034mshameem@amis.edu.ph', 'Amis@2N5Y059', 'Grade 4', '2026-2027', NOW(), NOW());

-- Student: PRINCE KHALIFA SANTOS DIZON (Grade 5)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY DIZON', 'parent.dizon.869@amis.test', 'parent_dizon_535', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 5', 'PRINCE KHALIFA', 'DIZON', 'SANTOS', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.dizon.869@amis.test', 'FAMILY DIZON', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260035', '260035dprince@amis.edu.ph', '260035dprince@amis.edu.ph', 'Amis@NZEOD57', 'Grade 5', '2026-2027', NOW(), NOW());

-- Student: MARYAM UTHMAN TOLENTINO SANTOS (Grade 5)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY SANTOS', 'parent.santos.290@amis.test', 'parent_santos_680', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 5', 'MARYAM UTHMAN', 'SANTOS', 'TOLENTINO', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.santos.290@amis.test', 'FAMILY SANTOS', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260036', '260036smaryam@amis.edu.ph', '260036smaryam@amis.edu.ph', 'Amis@6C5PP97', 'Grade 5', '2026-2027', NOW(), NOW());

-- Student: ABDURRAHMAN MUKARRAMA UNDANG (Grade 5)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY UNDANG', 'parent.undang.820@amis.test', 'parent_undang_396', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 5', 'ABDURRAHMAN', 'UNDANG', 'MUKARRAMA', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.undang.820@amis.test', 'FAMILY UNDANG', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260037', '260037uabdurrahman@amis.edu.ph', '260037uabdurrahman@amis.edu.ph', 'Amis@VS2NC56', 'Grade 5', '2026-2027', NOW(), NOW());

-- Student: SARAH UTHMAN TOLENTINO SANTOS (Grade 6)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY SANTOS', 'parent.santos.776@amis.test', 'parent_santos_622', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 6', 'SARAH UTHMAN', 'SANTOS', 'TOLENTINO', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.santos.776@amis.test', 'FAMILY SANTOS', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260038', '260038ssarah@amis.edu.ph', '260038ssarah@amis.edu.ph', 'Amis@7MQB299', 'Grade 6', '2026-2027', NOW(), NOW());

-- Student: MESHAEL SALI ARASAD (Grade 6)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ARASAD', 'parent.arasad.238@amis.test', 'parent_arasad_258', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 6', 'MESHAEL', 'ARASAD', 'SALI', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.arasad.238@amis.test', 'FAMILY ARASAD', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260039', '260039ameshael@amis.edu.ph', '260039ameshael@amis.edu.ph', 'Amis@4AT4K47', 'Grade 6', '2026-2027', NOW(), NOW());

-- Student: ABDULAZIZ GABRIEL ISMALI (Grade 6)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ISMALI', 'parent.ismali.143@amis.test', 'parent_ismali_997', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 6', 'ABDULAZIZ', 'ISMALI', 'GABRIEL', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.ismali.143@amis.test', 'FAMILY ISMALI', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260040', '260040iabdulaziz@amis.edu.ph', '260040iabdulaziz@amis.edu.ph', 'Amis@2KNNB34', 'Grade 6', '2026-2027', NOW(), NOW());

-- Student: KHALIL MUDAG PANGANDAMAN (Grade 6)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY PANGANDAMAN', 'parent.pangandaman.873@amis.test', 'parent_pangandaman_173', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 6', 'KHALIL', 'PANGANDAMAN', 'MUDAG', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.pangandaman.873@amis.test', 'FAMILY PANGANDAMAN', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260041', '260041pkhalil@amis.edu.ph', '260041pkhalil@amis.edu.ph', 'Amis@F1DAF79', 'Grade 6', '2026-2027', NOW(), NOW());

-- Student: EID RHIAN CELESTIAL SAGAYNO (Grade 7)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY SAGAYNO', 'parent.sagayno.160@amis.test', 'parent_sagayno_349', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 7', 'EID RHIAN', 'SAGAYNO', 'CELESTIAL', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.sagayno.160@amis.test', 'FAMILY SAGAYNO', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260042', '260042seid@amis.edu.ph', '260042seid@amis.edu.ph', 'Amis@HHSTV48', 'Grade 7', '2026-2027', NOW(), NOW());

-- Student: GIULIANAH AGONIA OLIS (Grade 7)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY OLIS', 'parent.olis.566@amis.test', 'parent_olis_676', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 7', 'GIULIANAH', 'OLIS', 'AGONIA', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.olis.566@amis.test', 'FAMILY OLIS', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260043', '260043ogiulianah@amis.edu.ph', '260043ogiulianah@amis.edu.ph', 'Amis@KYBZT56', 'Grade 7', '2026-2027', NOW(), NOW());

-- Student: JOHANAH ABDUL MAULA ANDAYA (Grade 7)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ANDAYA', 'parent.andaya.295@amis.test', 'parent_andaya_520', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 7', 'JOHANAH ABDUL', 'ANDAYA', 'MAULA', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.andaya.295@amis.test', 'FAMILY ANDAYA', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260044', '260044ajohanah@amis.edu.ph', '260044ajohanah@amis.edu.ph', 'Amis@CDCER64', 'Grade 7', '2026-2027', NOW(), NOW());

-- Student: RASHEED GUERERO SAID (Grade 7)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY SAID', 'parent.said.955@amis.test', 'parent_said_239', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 7', 'RASHEED', 'SAID', 'GUERERO', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.said.955@amis.test', 'FAMILY SAID', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260045', '260045srasheed@amis.edu.ph', '260045srasheed@amis.edu.ph', 'Amis@BSPT769', 'Grade 7', '2026-2027', NOW(), NOW());

-- Student: YARAH KUDARAT ALZAHRANI (Grade 8)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ALZAHRANI', 'parent.alzahrani.618@amis.test', 'parent_alzahrani_556', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 8', 'YARAH', 'ALZAHRANI', 'KUDARAT', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.alzahrani.618@amis.test', 'FAMILY ALZAHRANI', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260046', '260046ayarah@amis.edu.ph', '260046ayarah@amis.edu.ph', 'Amis@EKFE421', 'Grade 8', '2026-2027', NOW(), NOW());

-- Student: ABDULRAHMAN OLIMPAIN KATOG (Grade 8)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY KATOG', 'parent.katog.199@amis.test', 'parent_katog_264', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 8', 'ABDULRAHMAN', 'KATOG', 'OLIMPAIN', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.katog.199@amis.test', 'FAMILY KATOG', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260047', '260047kabdulrahman@amis.edu.ph', '260047kabdulrahman@amis.edu.ph', 'Amis@KXDDF89', 'Grade 8', '2026-2027', NOW(), NOW());

-- Student: RAYYAN MANSARI JAMMANG (Grade 8)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY JAMMANG', 'parent.jammang.232@amis.test', 'parent_jammang_505', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 8', 'RAYYAN', 'JAMMANG', 'MANSARI', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.jammang.232@amis.test', 'FAMILY JAMMANG', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260048', '260048jrayyan@amis.edu.ph', '260048jrayyan@amis.edu.ph', 'Amis@VCNR026', 'Grade 8', '2026-2027', NOW(), NOW());

-- Student: YANI VERA NOAH TABAY (Grade 8)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY TABAY', 'parent.tabay.565@amis.test', 'parent_tabay_491', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Face-to-Face', 'NA', 'Grade 8', 'YANI VERA', 'TABAY', 'NOAH', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.tabay.565@amis.test', 'FAMILY TABAY', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260049', '260049tyani@amis.edu.ph', '260049tyani@amis.edu.ph', 'Amis@XCKOC94', 'Grade 8', '2026-2027', NOW(), NOW());

-- Student: KHALILA ZOE DEBELEN GANDAMRA (Grade 9)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY GANDAMRA', 'parent.gandamra.410@amis.test', 'parent_gandamra_510', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 9', 'KHALILA ZOE', 'GANDAMRA', 'DEBELEN', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.gandamra.410@amis.test', 'FAMILY GANDAMRA', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260050', '260050gkhalila@amis.edu.ph', '260050gkhalila@amis.edu.ph', 'Amis@WIY0O89', 'Grade 9', '2026-2027', NOW(), NOW());

-- Student: OMAR NASHAT LOCTON ISSA (Grade 10)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY ISSA', 'parent.issa.157@amis.test', 'parent_issa_248', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 10', 'OMAR NASHAT', 'ISSA', 'LOCTON', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.issa.157@amis.test', 'FAMILY ISSA', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260051', '260051iomar@amis.edu.ph', '260051iomar@amis.edu.ph', 'Amis@GFFSL98', 'Grade 10', '2026-2027', NOW(), NOW());

-- Student: JAN MATHEW ALEXANDER TABAY (Grade 10)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY TABAY', 'parent.tabay.108@amis.test', 'parent_tabay_159', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Face-to-Face', 'NA', 'Grade 10', 'JAN MATHEW', 'TABAY', 'ALEXANDER', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.tabay.108@amis.test', 'FAMILY TABAY', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260052', '260052tjan@amis.edu.ph', '260052tjan@amis.edu.ph', 'Amis@DEMVU58', 'Grade 10', '2026-2027', NOW(), NOW());

-- Student: KAMILAH CASSANDRA AGONIA OLIS (Grade 11)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY OLIS', 'parent.olis.194@amis.test', 'parent_olis_778', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Flexible Online Learning', 'NA', 'Grade 11', 'KAMILAH CASSANDRA', 'OLIS', 'AGONIA', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.olis.194@amis.test', 'FAMILY OLIS', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260053', '260053okamilah@amis.edu.ph', '260053okamilah@amis.edu.ph', 'Amis@IXBJT59', 'Grade 11', '2026-2027', NOW(), NOW());

-- Student: RASHID MANGUDADATU MAGNO (Grade 11)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MAGNO', 'parent.magno.587@amis.test', 'parent_magno_644', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 11', 'RASHID', 'MAGNO', 'MANGUDADATU', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.magno.587@amis.test', 'FAMILY MAGNO', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260054', '260054mrashid@amis.edu.ph', '260054mrashid@amis.edu.ph', 'Amis@9XJU252', 'Grade 11', '2026-2027', NOW(), NOW());

-- Student: ALEXANDRA BRIELLE TABAY (Grade 11)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY TABAY', 'parent.tabay.911@amis.test', 'parent_tabay_184', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'New', 'Face-to-Face', 'NA', 'Grade 11', 'ALEXANDRA', 'TABAY', 'BRIELLE', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.tabay.911@amis.test', 'FAMILY TABAY', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260055', '260055talexandra@amis.edu.ph', '260055talexandra@amis.edu.ph', 'Amis@YPGWM85', 'Grade 11', '2026-2027', NOW(), NOW());

-- Student: HASANAH COMAYOG MAMA (Grade 11)
INSERT INTO users (name, email, username, password, role, account_status, created_at, updated_at) VALUES ('FAMILY MAMA', 'parent.mama.748@amis.test', 'parent_mama_965', '$2y$12$Sfe8srn/lYfLkT0fbPVFZ.A5atUPwsa5aQA7/VZEKlYyUya8X3nVG', 'applicant', 'verified', NOW(), NOW());
SET @last_user_id = LAST_INSERT_ID();
INSERT INTO enrollment_applicants (user_id, student_type, learning_mode, lrn, grade_level, first_name, last_name, middle_name, gender, date_of_birth, place_of_birth, religion, country, address, mobile_number, parent_mobile, parent_email, emergency_name, emergency_relationship, emergency_phone, school_year, last_step, status, created_at, updated_at) VALUES (@last_user_id, 'Old', 'Flexible Online Learning', 'NA', 'Grade 11', 'HASANAH', 'MAMA', 'COMAYOG', 'male', '2018-01-01', 'Davao City', 'Islam', 'Philippines', 'Davao City', '+639000000000', '+639000000000', 'parent.mama.748@amis.test', 'FAMILY MAMA', 'Parent', '+639000000000', '2026-2027', 7, 'approved', NOW(), NOW());
SET @last_applicant_id = LAST_INSERT_ID();
INSERT INTO students (user_id, enrollment_applicant_id, student_number, school_email, ms_email, temp_password, grade_level, school_year, created_at, updated_at) VALUES (@last_user_id, @last_applicant_id, '260056', '260056mhasanah@amis.edu.ph', '260056mhasanah@amis.edu.ph', 'Amis@CLLDU83', 'Grade 11', '2026-2027', NOW(), NOW());

COMMIT;