[program:laravel-horizon]
process_name=%(program_name)s
command=php /home2/amisdavc/admin.amis.edu.ph/artisan horizon
autostart=true
autorestart=true
user=amisdavc
redirect_stderr=true
stdout_logfile=/home2/amisdavc/admin.amis.edu.ph/storage/logs/horizon.log
stopwaitsecs=3600
