<x-admin-layout title="Class & Section Mapping">
    @include('admin.microsoft-roster._alerts')
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-[10px] font-black uppercase tracking-widest text-blue-700">Microsoft Integration</p><h1 class="text-2xl font-extrabold text-slate-950">Class & Section Mapping</h1><p class="mt-1 text-sm text-slate-500">Review parser suggestions and explicitly map Teams to AMIS academic records.</p></div><form method="GET"><select name="status" onchange="this.form.submit()" class="rounded-xl border-slate-200 text-sm"><option value="">All statuses</option>@foreach(['pending','suggested','confirmed','ignored'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></form></div>
    <div class="mb-5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-900">Mapping is review-only. Confirming a suggestion does not update student enrollment, official grade levels, or official sections.</div>
    <x-card title="Team Mapping Review" subtitle="Detected values remain suggestions until an administrator confirms them">
        <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-500"><tr><th class="px-4 py-3">Team</th><th class="px-4 py-3">Detected Grade</th><th class="px-4 py-3">Detected Section</th><th class="px-4 py-3">Gender</th><th class="px-4 py-3">Shift</th><th class="px-4 py-3">Program</th><th class="px-4 py-3">Confidence</th><th class="px-4 py-3">Mapping Status</th><th class="px-4 py-3">Actions</th></tr></thead>
        <tbody class="divide-y divide-slate-100">@forelse($teams as $team)@php($detected=$team->mapping?->detection_payload ?? [])<tr><td class="px-4 py-3 font-bold text-slate-900">{{ $team->display_name }}</td><td class="px-4 py-3">{{ $detected['grade_level'] ?? '—' }}</td><td class="px-4 py-3">{{ $detected['section_name'] ?? '—' }}</td><td class="px-4 py-3 capitalize">{{ $detected['gender_group'] ?? '—' }}</td><td class="px-4 py-3">{{ $detected['shift'] ?? '—' }}</td><td class="px-4 py-3 capitalize">{{ $detected['program_type'] ?? $team->team_category ?? '—' }}</td><td class="px-4 py-3">{{ $team->mapping?->confidence !== null ? number_format((float)$team->mapping->confidence,0).'%' : '—' }}</td><td class="px-4 py-3"><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black uppercase">{{ $team->mapping?->mapping_status ?? 'pending' }}</span></td><td class="px-4 py-3"><div class="flex flex-wrap gap-2"><a href="{{ route('admin.microsoft-roster.mappings.edit',$team) }}" class="font-bold text-blue-700">Review / Edit</a><form method="POST" action="{{ route('admin.microsoft-roster.mappings.ignore',$team) }}">@csrf<button class="font-bold text-amber-700" onclick="return confirm('Mark this Team as not an official class?')">Ignore</button></form>@if($team->mapping)<form method="POST" action="{{ route('admin.microsoft-roster.mappings.destroy',$team) }}">@csrf @method('DELETE')<button class="font-bold text-rose-700" onclick="return confirm('Remove this local mapping?')">Remove</button></form>@endif</div></td></tr>@empty<tr><td colspan="9" class="px-4 py-12 text-center text-slate-500">No synchronized Teams are available for mapping.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $teams->links() }}</div>
    </x-card>
</x-admin-layout>
