<x-admin-layout title="Map Microsoft Team">
    @include('admin.microsoft-roster._alerts')
    @php($detected=$team->mapping?->detection_payload ?? [])
    <div class="mb-6"><a href="{{ route('admin.microsoft-roster.mappings') }}" class="mb-2 inline-block text-xs font-bold text-blue-700">← Class & Section Mapping</a><h1 class="text-2xl font-extrabold text-slate-950">{{ $team->display_name }}</h1><p class="mt-1 text-sm text-slate-500">Review the detected values and select the official AMIS references manually.</p></div>
    <div class="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
        <x-card title="Parser Suggestion" subtitle="Names are never used for automatic account or enrollment changes"><div class="grid grid-cols-2 gap-4 p-5 text-sm">@foreach(['Detected Grade'=>'grade_level','Detected Section'=>'section_name','Detected Gender'=>'gender_group','Detected Shift'=>'shift','Detected Program'=>'program_type','School Year'=>'school_year'] as $label=>$key)<div><span class="block text-[10px] font-black uppercase tracking-widest text-slate-400">{{ $label }}</span><strong class="capitalize">{{ $detected[$key] ?? 'Not detected' }}</strong></div>@endforeach<div><span class="block text-[10px] font-black uppercase tracking-widest text-slate-400">Confidence</span><strong>{{ isset($detected['confidence']) ? number_format($detected['confidence'],0).'%' : '—' }}</strong></div><div><span class="block text-[10px] font-black uppercase tracking-widest text-slate-400">Mapping Status</span><strong class="capitalize">{{ $team->mapping?->mapping_status ?? 'pending' }}</strong></div></div></x-card>
        <x-card title="Confirmed Local Mapping" subtitle="This stores an integration mapping only"><form method="POST" action="{{ route('admin.microsoft-roster.mappings.update',$team) }}" class="grid gap-4 p-5 sm:grid-cols-2">@csrf @method('PUT')
            <label class="text-sm font-bold text-slate-700">School Year<select name="school_year_id" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Not selected</option>@foreach($schoolYears as $year)<option value="{{ $year->id }}" @selected((string)old('school_year_id',$team->mapping?->school_year_id)===(string)$year->id)>{{ $year->code }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">Grade Level<select name="grade_level_id" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Not selected</option>@foreach($gradeLevels as $grade)<option value="{{ $grade->id }}" @selected((string)old('grade_level_id',$team->mapping?->grade_level_id)===(string)$grade->id)>{{ $grade->name }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700 sm:col-span-2">Section<select name="section_id" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Not an official section / not selected</option>@foreach($sections as $section)<option value="{{ $section->id }}" @selected((string)old('section_id',$team->mapping?->section_id)===(string)$section->id)>{{ $section->grade_level }} — {{ $section->name }} ({{ $section->gender ?? 'mixed' }}, {{ $section->shift ?? 'no shift' }})</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">Shift<select name="shift" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Not selected</option>@foreach(['1st Shift','2nd Shift'] as $value)<option @selected(old('shift',$team->mapping?->shift)===$value)>{{ $value }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">Gender Group<select name="gender_group" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Not selected</option>@foreach(['boys','girls','mixed'] as $value)<option value="{{ $value }}" @selected(old('gender_group',$team->mapping?->gender_group)===$value)>{{ ucfirst($value) }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">Program<select name="program_type" class="mt-1 w-full rounded-xl border-slate-200">@foreach(['academic','isal','halaqah','general','other'] as $value)<option value="{{ $value }}" @selected(old('program_type',$team->mapping?->program_type ?? $detected['program_type'] ?? 'academic')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></label>
            <label class="flex items-center gap-2 self-end rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold"><input type="checkbox" name="not_official_class" value="1" @checked(old('not_official_class',$team->mapping?->not_official_class ?? $detected['not_official_class'] ?? false))> Not an official class section</label>
            <label class="sm:col-span-2 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-900"><input class="mt-0.5" type="checkbox" name="confirm_mapping" value="1" required> I verified this mapping. I understand that it links review data only and does not change official student sections.</label>
            <div class="sm:col-span-2 flex justify-end"><button class="rounded-xl bg-blue-700 px-5 py-2.5 text-sm font-bold text-white">Confirm Mapping</button></div>
        </form></x-card>
    </div>
</x-admin-layout>
