<x-admin-layout title="Review Microsoft Account Match">
    @include('admin.microsoft-roster._alerts')
    <div class="mb-6"><a href="{{ route('admin.microsoft-roster.unmatched') }}" class="mb-2 inline-block text-xs font-bold text-blue-700">← Unmatched Accounts</a><h1 class="text-2xl font-extrabold text-slate-950">Review Match</h1><p class="mt-1 text-sm text-slate-500">Find an exact AMIS record, then confirm the link explicitly.</p></div>
    <div class="mb-6 grid gap-4 lg:grid-cols-3"><div class="rounded-2xl border border-blue-100 bg-blue-50 p-5 lg:col-span-2"><div class="text-[10px] font-black uppercase tracking-widest text-blue-600">Microsoft Account</div><div class="mt-2 text-xl font-extrabold text-slate-950">{{ $membership->display_name }}</div><div class="mt-1 text-sm text-slate-600">{{ $membership->email ?? $membership->user_principal_name ?? 'No email returned' }}</div><div class="mt-4 flex flex-wrap gap-2">@foreach($teams as $team)<span class="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-700">{{ $team }}</span>@endforeach</div></div><div class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div class="text-[10px] font-black uppercase tracking-widest text-amber-700">Warning</div><p class="mt-2 text-sm font-semibold leading-6 text-amber-950">This will link the Microsoft account to the selected AMIS record. Please verify the account carefully.</p></div></div>
    <form method="GET" class="mb-6 flex gap-2"><input name="search" value="{{ $search }}" required placeholder="Search AMIS ID, student/faculty name, or email" class="min-w-0 flex-1 rounded-xl border-slate-200"><button class="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">Find AMIS Record</button></form>
    @if($search !== '')
        <div class="grid gap-6 xl:grid-cols-2">
            <x-card title="Students" subtitle="Exact record selection"><div class="divide-y divide-slate-100">@forelse($students as $student)<form method="POST" action="{{ route('admin.microsoft-roster.matches.store',$membership) }}" class="flex items-center justify-between gap-4 p-4">@csrf<input type="hidden" name="target_type" value="student"><input type="hidden" name="target_id" value="{{ $student->id }}"><div><div class="font-bold text-slate-900">{{ $student->user?->name ?? $student->school_email }}</div><div class="text-xs text-slate-500">AMIS ID {{ $student->student_number }} · {{ $student->school_email }}</div></div><label class="flex items-center gap-2"><input type="checkbox" name="confirm_match" value="1" required><button class="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white">Confirm Student</button></label></form>@empty<p class="p-5 text-sm text-slate-500">No student records matched the search.</p>@endforelse</div></x-card>
            <x-card title="Faculty / Staff" subtitle="Teacher and authorized local accounts"><div class="divide-y divide-slate-100">@forelse($faculty as $user)<form method="POST" action="{{ route('admin.microsoft-roster.matches.store',$membership) }}" class="flex items-center justify-between gap-4 p-4">@csrf<input type="hidden" name="target_type" value="faculty"><input type="hidden" name="target_id" value="{{ $user->id }}"><div><div class="font-bold text-slate-900">{{ $user->name }}</div><div class="text-xs text-slate-500">{{ $user->email }} · {{ ucfirst($user->role) }}</div></div><label class="flex items-center gap-2"><input type="checkbox" name="confirm_match" value="1" required><button class="rounded-lg bg-indigo-700 px-3 py-2 text-xs font-bold text-white">Confirm Account</button></label></form>@empty<p class="p-5 text-sm text-slate-500">No faculty or staff accounts matched the search.</p>@endforelse</div></x-card>
        </div>
    @endif
    @if($membership->match_method === 'manual')<form method="POST" action="{{ route('admin.microsoft-roster.matches.destroy',$membership) }}" class="mt-6">@csrf @method('DELETE')<button class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-2.5 text-sm font-bold text-rose-700" onclick="return confirm('Remove this manual link?')">Remove Existing Manual Match</button></form>@endif
</x-admin-layout>
